// Mutations for Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREMENT_ITEM_QTY_IN_CART = 'DECREMENT_ITEM_QTY_IN_CART';
export const INCREMENT_ITEM_QTY_IN_CART = 'INCREMENT_ITEM_QTY_IN_CART';
export const DECREMENT_ITEM_QTY_IN_INVENTORY = 'DECREMENT_ITEM_QTY_IN_INVENTORY';
export const INCREMENT_ITEM_QTY_IN_INVENTORY = 'INCREMENT_ITEM_QTY_IN_INVENTORY';

// Mutations for Filters
export const UPDATE_CATEGORIES_FILTER = 'UPDATE_CATEGORIES_FILTER';
export const UPDATE_MATERIALS_FILTER = 'UPDATE_MATERIALS_FILTER';
export const UPDATE_ADDITIONAL_FILTER = 'UPDATE_ADDITIONAL_FILTER';
export const UPDATE_WIDTH_FILTER = 'UPDATE_WIDTH_FILTER';

// Mutations for recent products
export const FETCH_RECENT_SEARCH_PRODUCTS = 'FETCH_RECENT_SEARCH_PRODUCTS';